import { IconType } from "react-icons";
import {
  LuGraduationCap,
  LuFlaskConical,
  LuRoute,
  LuMilestone,
  LuZap,
  LuBrain,
  LuBookOpenCheck,
  LuMic,
  LuLanguages,
  LuLibrary,
  LuVolume2,
  LuPenLine,
  LuTrendingUp,
  LuHouse,
  LuInfo,
  LuPhone,
  LuColumns2,
  LuArrowRight,
  LuMoveRight,
  LuSparkles,
  LuCirclePlay,
  LuCircleUser,
  LuLayoutDashboard,
  LuTrophy,
  LuClock,
  LuCalendar,
  LuSettings,
  LuLogOut,
  LuHistory,
  LuUsers,
  LuSearch,
  LuMail,
  LuLock,
  LuCircleCheck,
  LuCircleAlert,
  LuHandshake,
  LuGem,
  LuBan,
  LuLockKeyhole,
  LuKeyRound,
  LuDownload,
} from "react-icons/lu";

import {
  FaFacebook,
  FaApple,
  FaInstagram,
  FaXTwitter,
  FaLinkedin,
  FaWhatsapp,
  FaTelegram,
  FaMessage,
  FaYoutube,
  FaTiktok,
  FaGoogle,
} from "react-icons/fa6";

export const SpeakUpIcons = {
  // Academia y Metodología
  academy: LuGraduationCap,
  lab: LuFlaskConical,
  roadmap: LuRoute,
  milestone: LuMilestone,
  quickTip: LuZap,
  logic: LuBrain,
  lessonDone: LuBookOpenCheck,
  speaking: LuMic,
  audio: LuVolume2,
  writing: LuPenLine,
  languages: LuLanguages,
  resources: LuLibrary,
  progress: LuTrendingUp,

  // Navegación y Conversión
  home: LuHouse,
  about: LuInfo,
  contact: LuPhone,
  catalog: LuColumns2,
  arrowRight: LuArrowRight,
  ctaArrow: LuMoveRight,
  premium: LuSparkles,
  play: LuCirclePlay,

  // Dashboard y Usuario
  profile: LuCircleUser,
  dashboard: LuLayoutDashboard,
  achievement: LuTrophy,
  studyTime: LuClock,
  schedule: LuCalendar,
  settings: LuSettings,
  logout: LuLogOut,
  history: LuHistory,
  community: LuUsers,

  // Interfaz y Feedback
  search: LuSearch,
  email: LuMail,
  password: LuLock,
  success: LuCircleCheck,
  warning: LuCircleAlert,
  alliance: LuHandshake,
  diamond: LuGem,
  blocked: LuBan,
  secure: LuLockKeyhole,
  download: LuDownload,
  accessKey: LuKeyRound,

  // Redes Sociales y Auth
  facebook: FaFacebook,
  instagram: FaInstagram,
  twitter: FaXTwitter,
  linkedin: FaLinkedin,
  whatsapp: FaWhatsapp,
  youtube: FaYoutube,
  tiktok: FaTiktok,
  google: FaGoogle,
  apple: FaApple,
  telegram: FaTelegram,
  message: FaMessage,
} as const;

export type SpeakUpIconKey = keyof typeof SpeakUpIcons;
export type SpeakUpIconComponent = IconType;